var hierarchy =
[
    [ "C_DOTAGamerulesProxy", "classC__DOTAGamerulesProxy.html", null ],
    [ "C_DOTAPlayerController", "classC__DOTAPlayerController.html", null ],
    [ "C_DOTATeam", "classC__DOTATeam.html", null ],
    [ "CBaseEntity", "classCBaseEntity.html", null ],
    [ "CCvar", "classCCvar.html", null ],
    [ "CCvarNode", "classCCvarNode.html", null ],
    [ "CCvarNodes", "classCCvarNodes.html", null ],
    [ "CDOTACamera", "classCDOTACamera.html", null ],
    [ "CDOTAGamerules", "classCDOTAGamerules.html", null ],
    [ "CEngineClient", "classCEngineClient.html", null ],
    [ "CEntityIdentity", "classCEntityIdentity.html", null ],
    [ "CGameEntitySystem", "classCGameEntitySystem.html", null ],
    [ "CHandle", "classCHandle.html", null ],
    [ "ClassDescription", "classClassDescription.html", null ],
    [ "ClassDescription_Container", "classClassDescription__Container.html", null ],
    [ "ConfigManager", "classConfigManager.html", null ],
    [ "CSchemaClassBinding", "classCSchemaClassBinding.html", null ],
    [ "CSchemaSystem", "classCSchemaSystem.html", null ],
    [ "CSchemaSystemTypeScope", "classCSchemaSystemTypeScope.html", null ],
    [ "CSchemaType_Builtin", "classCSchemaType__Builtin.html", null ],
    [ "CSource2Client", "classCSource2Client.html", null ],
    [ "GameData", "classGameData.html", null ],
    [ "Hacks", "classHacks.html", null ],
    [ "Interface", "classInterface.html", [
      [ "CreateInterface", "classCreateInterface.html", null ]
    ] ],
    [ "Memory", "classMemory.html", null ],
    [ "Memory::ModuleInfo", "structMemory_1_1ModuleInfo.html", null ],
    [ "CreateInterface::ModuleInterfaces", "structCreateInterface_1_1ModuleInterfaces.html", null ],
    [ "Patches", "classPatches.html", null ],
    [ "Patches::PatchInfo", "structPatches_1_1PatchInfo.html", null ],
    [ "Patches::Patterns", "structPatches_1_1Patterns.html", null ],
    [ "ProcessHandle", "classProcessHandle.html", null ],
    [ "Scanner", "classScanner.html", null ],
    [ "SchemaClassFieldData_t", "classSchemaClassFieldData__t.html", null ],
    [ "SchemaName", "classSchemaName.html", null ],
    [ "SchemaParentInfo", "classSchemaParentInfo.html", null ],
    [ "SemVer", "structSemVer.html", null ],
    [ "Updater", "classUpdater.html", null ],
    [ "Utils", "classUtils.html", null ],
    [ "WebVer", "structWebVer.html", null ]
];