name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        
      - name: Build English documentation
        run: |
          mkdir -p docs/en
          doxygen Doxyfile_en

      - name: Build Russian documentation
        run: |
          mkdir -p docs/ru
          doxygen Doxyfile_ru

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          enable_jekyll: false
